import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/ThemeContext";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Toast from "@/components/Toast/Toast";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  style: ["italic", "normal"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Steel App",
  description: "Generated by create next app",
  icons: [
    {
      media: "(prefers-color-scheme: light)",
      url: "/images/logo.png",
      href: "/images/logo.png",
    },
    {
      media: "(prefers-color-scheme: dark)",
      url: "/images/logo-dark.png",
      href: "/images/logo-dark.png",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider>
          <Toast />
          <main className="font-normal">
            <Header />
            <div className="flex max-w-[1400px] m-auto">
              <div className="flex w-screen px-4">{children}</div>
            </div>
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
